name: Build AdGuard DNS filter

on:
  push:
  schedule:
    - cron: '0 */6 * * *' # Every 6th hour

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pull upstream
        run: |
          git config user.email "git@github.com"
          git config user.name "GitHub Actions"
          git config pull.rebase true
          git pull https://github.com/AdguardTeam/AdGuardSDNSFilter "${{ github.head_ref || github.ref_name }}"
          git push --force origin "${{ github.head_ref || github.ref_name }}"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn
        run: |
          yarn install
          yarn run build

      - name: prepare deploy
        run: |
          mkdir build
          cp -rf Filters build/
        env:
          CI: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
